### ISSUE TITLE
Decode TLV PubkeyScript causes DataIntegrityError

### ISSUE THREAD

**Issue by oacdutra** [LNP-WG/lightning_encoding#6] opened 2023-03-11 18:20 UTC
The `open_channel` message (bolt2) has a field called `shutdown_scriptpubkey`; this field is optional. The lightning decode returns DataIntegrityError when this field is empty.

I'm not sure how to solve this issue, but the TLV fields need a way to check if vector bytes are empty. If true, "skip" the parsing process.

**Comment by dr-orlovsky** [comment] 2023-03-12 09:51
Sorry, why you created a new duplicate of the issue https://github.com/LNP-WG/lightning_encoding/issues/2? I just solved it yesterday with https://github.com/LNP-WG/lightning_encoding/pull/4?

**Comment by dr-orlovsky** [comment] 2023-03-12 09:53
Ok, I see your explanations in https://github.com/LNP-WG/lnp-core/pull/30#pullrequestreview-1335911092. Can you pls delete this duplicate issue and re-open #2?

**Comment by oacdutra** [comment] 2023-03-12 14:57
Hi @dr-orlovsky, for some reason, I cannot open #2

**Closed as not planned** 2023-03-12 14:57 UTC
Labels: duplicate, invalid

**Comment by dr-orlovsky** [comment] 2023-03-12 16:34
I have re-opened it
